### PR TITLE
Improve the stopping condition method

### PR DESCRIPTION
**Pull request by AmintorDusko**
**Context:**
Improve the `stopping_condition` method, and expand tests to cover tape execution.

**Description of the Change:**

- Refactor `stopping_condition` to rely on the `supports_operation` method.
- Expand tests, to cover tape execution.
- Add a .gitignore file.

**Benefits:**
Operations will only be decomposed if not supported by Lightning-Kokkos.

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Comment by AmintorDusko** [comment]
Waiting for PR #14 to update the changelog and the CI tests.

**Comment by AmintorDusko** [comment]
[sc-30494]

**Review by mlxd — APPROVED** [review]
Matches the other lightning packages. Thanks Amintor

**Review by multiphaseCFD — APPROVED** [review]
Thanks Amintor for the nice work!

**Pull request merged**
